# Generated by Django 4.2.5 on 2023-09-22 09:57

from django.db import migrations
import news.custom_field


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_feed_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='special',
            field=news.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_homepage',
            field=news.custom_field.CustomBooleanField(),
        ),
    ]
