# Generated by Django 4.2.5 on 2023-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
